name: Sync Public Repository

on:
  push:
    branches: [opensource]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'mynzai/starter-template-DNA'
    
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: opensource
      
      - name: Push to public repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add public https://x-access-token:${GITHUB_TOKEN}@github.com/mynzai/starter-template-DNA-app.git
          git push public opensource:main --force